"""Tests for data provenance detection in postprocessor."""
import pytest

from scripts.postprocess import detect_data_source


def test_detect_synthetic_data(tmp_path):
    """Directories with .synthetic marker should be detected as synthetic."""
    job_dir = tmp_path / "cd34_vs_test"
    job_dir.mkdir()
    (job_dir / ".synthetic").write_text("generated by generate_test_af3_data.py")
    assert detect_data_source(str(job_dir)) == "synthetic"


def test_detect_real_data(tmp_path):
    """Directories without .synthetic marker should be detected as af3_server."""
    job_dir = tmp_path / "cd34_vs_test"
    job_dir.mkdir()
    assert detect_data_source(str(job_dir)) == "af3_server"


def test_detect_real_data_with_terms(tmp_path):
    """Directories with terms_of_use.md but no .synthetic marker are real."""
    job_dir = tmp_path / "cd34_vs_test"
    job_dir.mkdir()
    (job_dir / "terms_of_use.md").write_text("AF3 terms")
    assert detect_data_source(str(job_dir)) == "af3_server"
